# Generated by Django 5.2.1 on 2025-05-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Digital Marketing', 'Digital Marketing'), ('Telicaller', 'TeliCaller'), ('Admin', 'Admin')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField()),
                ('description', models.TextField()),
                ('Priority', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], default='New', max_length=50)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='app.employee')),
            ],
        ),
    ]
