# Generated by Django 5.2.1 on 2025-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leads_status_alter_leads_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
