# Generated by Django 5.2.1 on 2025-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_leads_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Digital Marketing', 'Digital Marketing'), ('Telicaller', 'TeliCaller'), ('Admin', 'Admin')], default='Manager', max_length=50),
        ),
    ]
